-- =============================================================
-- E-COMMERCE DATABASE SCHEMA 
-- =============================================================
-- Database: ecommerce_db
create database ecommerce_db;
use ecommerce_db;
-- Tables: 
create table customers(
customer_id INT primary key,
name varchar(50) not null, 
city varchar(50),
email varchar(100) not null unique
); 
create table products (
product_id int primary key, 
product_name varchar(100) not null,
category varchar(50) not null, 
price decimal(10, 2) not null,
stock_quantity int not null check( stock_quantity>0)
);
create table orders( 
order_id int primary key, 
customer_id int not null, 
product_id int not null, 
quantity int not null check(quantity>0),
order_date date not null, 
status varchar(20) default 'pending' ,
foreign key (customer_id) references customers(customer_id),
foreign key (product_id) references products(product_id)
);

-- =============================================================
-- DATA VALIDATION 
-- =============================================================
-- check the number of records in each table 
select count(*) from customers;
select count(*) from products;
select count(*) from orders;
-- check for cutomers with missing emails
select * from customers 
where email is NULL;
-- check for duplicate customer emails
select email, count(*) as duplicate_emails 
from customers 
group by email 
having count(*)>1;
-- products with invalid or non-positive prices
select * from products 
where price <= 0; 
-- orders with invalid or non-positive quantities
select  * from orders
where quantity<= 0;
-- orders containing unexpected status values
select * from orders
where status not in ('Delivered', 'Pending', 'Cancelled', 'Returned');
--  orders referencing non-existent customers
select o. * 
from orders o 
left join customers c 
on o.customer_id= c.customer_id
where c.customer_id is null;

-- =============================================================
-- Exploratory Analysis
-- =============================================================

-- Identify the highest-priced products in the catalog
select product_name, category, price 
from products
order by price desc 
limit 10;
-- Cuatomers located in Delhi 
select name, email, city 
from customers
where city= "Delhi";
-- Explore the unique product categories 
select distinct category from products;
-- Most recent delivered orders 
select * from orders
where status= 'Delivered'
order by order_date desc
limit 10;
-- Explore products within a specific price range 
select * from products 
where price between 500 and 2000
order by price asc;
-- Customers across selected cities 
select city, name from customers 
where city in ('Delhi', 'Lucknow', 'Mumbai');
-- Large orders 
select customer_id, quantity 
from orders
where quantity > 5;
-- Orders that are placed during 2026 
select * from orders
where order_date between '2026-01-01' and '2026-12-31';
-- Details of cancelled and returned orders
select * from orders 
where status in ( 'Cancelled', 'Returned');
-- High priced electronics products 
select * from products
where category = "Electronics" and price > 5000;

-- =============================================================
-- Customer Analysis 
-- =============================================================

-- customer information for each order with status
select name, city, order_id, order_date, status
from customers c 
join orders o 
on c.customer_id= o.customer_id;
-- Product details for each order
select product_name, category, quantity, price, order_id 
from products p 
join orders o 
on p.product_id= o.product_id;
-- Complete order information 
select order_id,name,city,product_name,category,quantity,price,order_date,status 
from customers c 
join orders o 
on c.customer_id= o.customer_id
join products p 
on p.product_id=o.product_id;
-- Delhi orders
select name, order_id, quantity, city
from customers c 
join orders o
on c.customer_id= o.customer_id
where city = "Delhi"; 
-- Electronics orders
select order_id, product_name, category 
from products p 
join orders o 
on p.product_id= o.product_id
where category = "Electronics";
-- Revenue generated by each order
select order_id, product_name, quantity, price, price* quantity as total_amount
from products p 
join orders o 
on p.product_id=o.product_id; 
-- Delhi electronics orders 
select name, product_name, quantity, price*quantity as order_amount, city, category
from customers c 
join orders o 
on c.customer_id= o.customer_id
join products p 
on p.product_id= o.product_id
where city= "Delhi" AND category = "Electronics";
-- High quantity orders with customer and product details
select name, product_name, quantity 
from customers c 
join orders o 
on c.customer_id= o.customer_id
join products p 
on p.product_id= o.product_id
where quantity> 3;

-- =============================================================
-- AGGREGATIONS 
-- =============================================================

-- Number of orders by status 
select status, count(order_id) as order_count
from orders 
group by status;
-- Average product price by category
select category, avg(price) as avg_price
from products 
group by category; 
-- Total business revenue 
select sum(price* quantity) as total_revenue 
from products p 
join orders o 
on p.product_id=o.product_id;
-- Revenue generated by category 
select category, sum(price* quantity) as revenue
from products p 
join orders o 
on p.product_id=o.product_id
group by category;
-- Total spending by customer
select name, sum(price* quantity) as total_spending 
from customers c
join orders o 
on c.customer_id=o.customer_id
join products p 
on p.product_id=o.product_id
group by name;
-- Customers spending more than 10000 
select name, sum(price* quantity) as total_spending 
from customers c
join orders o 
on c.customer_id=o.customer_id
join products p 
on p.product_id=o.product_id
group by name
having sum(price* quantity) > 10000;
-- units sold by category  
select sum(quantity) as units_sold, category 
from products p 
join orders o 
on p.product_id= o.product_id
group by category;
-- Categories ranked by average product price
select category, avg(price) as avg_price
from products 
group by category 
order by avg(price) desc; 

-- =============================================================
-- SUBQUERIES
-- =============================================================

-- Products priced above the overall average product price 
select price, product_name, product_id from products 
where price > 
( select avg(price) from products);
-- Products priced below the average price of their category 
select p1.product_name, p1.price, p1.category 
from products as p1 
where p1.price < 
(select avg(p2.price) from products as p2
where p1.category=p2.category
group by category);
-- Customers who have placed atleast one order
select name from customers 
where customer_id IN 
( select customer_id from orders);
-- Customers who have never placed an order 
select name from customers 
where customer_id NOT IN 
( select customer_id from orders);
-- Highest priced product(s) 
select * from products 
where price =
(select max(price) from products);
-- Customers with total spending above 100,000
select name 
from customers 
where customer_id in 
( select o.customer_id
from orders o 
join products p 
on p.product_id= o.product_id
group by o.customer_id
having sum(p.price*o.quantity)>100000);

-- =============================================================
-- CTE-BASED ANALYSIS
-- =============================================================

-- -- identify the top 10 customers by total_spending 
with customer_spending as 
( select name,sum(price*quantity) as total_spending
from customers c 
join orders o 
on c.customer_id=o.customer_id
join products p 
on p.product_id=o.product_id 
group by name)
select * from customer_spending 
order by total_spending desc 
limit 10;  
-- Identify categories generating more than 500,000 in revenue
with category_revenue as 
( select category, sum(price*quantity) as total_revenue 
from products p 
join orders o 
on p.product_id= o.product_id
group by category )
select * from category_revenue 
where total_revenue> 500000;
-- Analyze monthly revenue across the available years
with revenue as 
( select month(order_date)  as month_ , year(order_date) as year_, sum(price*quantity) as total_revenue
from products p 
join orders o 
on p.product_id=o.product_id
group by month(order_date) , year(order_date))
select * from revenue
order by total_revenue desc;
-- Identify customers whose spending is above the average customer spending
with spending as 
(select name, sum(price*quantity) as total_spending
from customers c 
join orders o 
on c.customer_id= o.customer_id
join products p 
on p.product_id=o.product_id
group by name)
select * from spending 
where total_spending> 
(select avg(total_spending) 
from spending);
-- Identify products generating more than 50,000 in revenue
with product_revenue as 
( select p.product_name, sum(p.price*o.quantity) as revenue 
from products p 
join orders o 
on p.product_id=o.product_id
group by p.product_name)
select * from product_revenue 
where revenue> 50000
order by revenue desc;

-- =============================================================
-- WINDOW FUNCTION ANALYSIS
-- =============================================================

-- Rank products by total revenue
with product_revenue as 
( select p.product_name,p.product_id, sum(p.price*o.quantity) as revenue, rank() over 
( order by sum(p.price*o.quantity) desc) as rank_
from products p 
join orders o 
on p.product_id=o.product_id
group by p.product_name, p.product_id)
select * from product_revenue;
-- Identify the highest-revenue product within each category
with product_revenue  as 
(select product_name,category, sum(price*quantity) as revenue
from products p 
join orders o 
on p.product_id=o.product_id
group by category, product_name),
ranked_products as 
( select *, rank() over 
(partition by category order by revenue desc) as rank_ 
from product_revenue)
select * from ranked_products
where rank_=1;
-- Rank customers by total spending 
select name,  sum(price*quantity) as total_spending, rank () over
( order by sum(price*quantity) desc) as highest_spender
from customers c 
join orders o 
on c.customer_id=o.customer_id
join products p 
on p.product_id=o.product_id 
group by name;
-- Rank customers within their city based on total spending
select name, city, sum(price*quantity) as total_spending, rank () over
(partition by city order by sum(price*quantity) desc) as rank_
from customers c 
join orders o 
on c.customer_id=o.customer_id
join products p 
on p.product_id=o.product_id 
group by name,city;
-- Assign a unique spending rank to customers within each city
select name, city, sum(price*quantity) as total_spending, row_number () over 
(partition by city order by sum(price*quantity) desc) as row_num
from customers c
join orders o 
on c.customer_id= o.customer_id 
join products p 
on p.product_id=o.product_id
group by name, city
order by city, row_num;

-- =============================================================
-- ADDITIONAL ANALYSIS
-- =============================================================

-- Products performing above their category average
select p1.product_name, p1.category, p1.price
from products p1
where p1.price >
(select avg(p2.price)
from products p2
where p1.category=p2.category);

-- Customers with multiple orders
select name, count(o.order_id) as order_count
from customers c
join orders o
on c.customer_id=o.customer_id
group by name
having count(order_id)>1
order by order_count desc;

-- Products with no orders
select p.product_name, p.category
from products p
left join orders o
on p.product_id=o.product_id
where o.product_id is null;

-- Revenue by order status
select o.status, sum(p.price*o.quantity) as revenue
from orders o
join products p
on p.product_id=o.product_id
group by o.status
order by revenue desc;

-- Monthly revenue
select year(o.order_date) as year_, month(o.order_date) as month_,
sum(p.price*o.quantity) as revenue
from orders o
join products p
on p.product_id=o.product_id
group by year(o.order_date), month(o.order_date)
order by year_, month_;

-- Top 3 products in each category
with product_revenue as
(
select p.product_name, p.category,
sum(p.price*o.quantity) as revenue
from products p
join orders o
on p.product_id=o.product_id
group by p.product_name, p.category
),
ranked_products as
(
select *, rank() over
(partition by category order by revenue desc) as rank_
from product_revenue
)
select *
from ranked_products
where rank_<=3
order by category, rank_;

-- customer order frequency
select name, count(order_id) as total_orders,
sum(price*quantity) as total_spending
from customers c
join orders o
on c.customer_id=o.customer_id
join products p
on p.product_id=o.product_id
group by name
order by total_orders desc;

-- average order value
select avg(order_amount) as average_order_value
from
(select order_id, sum(price*quantity) as order_amount
from orders o
join products p
on p.product_id=o.product_id
group by order_id) as order_totals;

