-- =============================================================
-- Customer Analysis 
-- =============================================================

-- customer information for each order with status
select name, city, order_id, order_date, status
from customers c 
join orders o 
on c.customer_id= o.customer_id;
-- Product details for each order
select product_name, category, quantity, price, order_id 
from products p 
join orders o 
on p.product_id= o.product_id;
-- Complete order information 
select order_id,name,city,product_name,category,quantity,price,order_date,status 
from customers c 
join orders o 
on c.customer_id= o.customer_id
join products p 
on p.product_id=o.product_id;
-- Delhi orders
select name, order_id, quantity, city
from customers c 
join orders o
on c.customer_id= o.customer_id
where city = "Delhi"; 
-- Electronics orders
select order_id, product_name, category 
from products p 
join orders o 
on p.product_id= o.product_id
where category = "Electronics";
-- Revenue generated by each order
select order_id, product_name, quantity, price, price* quantity as total_amount
from products p 
join orders o 
on p.product_id=o.product_id; 
-- Delhi electronics orders 
select name, product_name, quantity, price*quantity as order_amount, city, category
from customers c 
join orders o 
on c.customer_id= o.customer_id
join products p 
on p.product_id= o.product_id
where city= "Delhi" AND category = "Electronics";
-- High quantity orders with customer and product details
select name, product_name, quantity 
from customers c 
join orders o 
on c.customer_id= o.customer_id
join products p 
on p.product_id= o.product_id
where quantity> 3;