-- =============================================================
-- AGGREGATIONS 
-- =============================================================

-- Number of orders by status 
select status, count(order_id) as order_count
from orders 
group by status;
-- Average product price by category
select category, avg(price) as avg_price
from products 
group by category; 
-- Total business revenue 
select sum(price* quantity) as total_revenue 
from products p 
join orders o 
on p.product_id=o.product_id;
-- Revenue generated by category 
select category, sum(price* quantity) as revenue
from products p 
join orders o 
on p.product_id=o.product_id
group by category;
-- Total spending by customer
select name, sum(price* quantity) as total_spending 
from customers c
join orders o 
on c.customer_id=o.customer_id
join products p 
on p.product_id=o.product_id
group by name;
-- Customers spending more than 10000 
select name, sum(price* quantity) as total_spending 
from customers c
join orders o 
on c.customer_id=o.customer_id
join products p 
on p.product_id=o.product_id
group by name
having sum(price* quantity) > 10000;
-- units sold by category  
select sum(quantity) as units_sold, category 
from products p 
join orders o 
on p.product_id= o.product_id
group by category;
-- Categories ranked by average product price
select category, avg(price) as avg_price
from products 
group by category 
order by avg(price) desc; 